
CREATE TABLE novel(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	title TEXT,
	created TEXT DEFAULT CURRENT_TIMESTAMP,
	modified TEXT DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE author( 
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name TEXT,
	email TEXT,
	password TEXT,
	created TEXT DEFAULT CURRENT_TIMESTAMP,
	modified TEXT DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE novel_author(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	created TEXT DEFAULT CURRENT_TIMESTAMP,
	modified TEXT DEFAULT CURRENT_TIMESTAMP,
	novelid INTEGER,
	authorid INTEGER,
	FOREIGN KEY(novelid) REFERENCES novel(id)
	FOREIGN KEY(authorid) REFERENCES author(id)
);


CREATE TABLE chapter(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	numeral INTEGER,
	title TEXT,
	time TEXT,
	setting TEXT,
	precis TEXT,
	synopsis TEXT,
	notes TEXT,
	color TEXT,
	created TEXT DEFAULT CURRENT_TIMESTAMP,
	modified TEXT DEFAULT CURRENT_TIMESTAMP,
	novelid INTEGER,
	FOREIGN KEY(novelid) REFERENCES novel(id)
);


CREATE TABLE annotation(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	content TEXT,
	target TEXT,
	start_index INTEGER,
	end_index INTEGER,
	created TEXT DEFAULT CURRENT_TIMESTAMP,
	modified TEXT DEFAULT CURRENT_TIMESTAMP,
	chapterid INTEGER,
	FOREIGN KEY(chapterid) REFERENCES chapter(id)
);
