CREATE TABLE account( 
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	username TEXT,
	email TEXT,
	passhash TEXT,
	role TEXT DEFAULT "guest",
	key TEXT,
	created TEXT DEFAULT CURRENT_TIMESTAMP,
	modified TEXT DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE novel(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	title TEXT,
	author TEXT,
	is_public INTEGER,
	userid INTEGER,
	created TEXT DEFAULT CURRENT_TIMESTAMP,
	modified TEXT DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(userid) REFERENCES user(id)
);


CREATE TABLE chapter(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	numeral INTEGER,
	title TEXT,
	time TEXT,
	setting TEXT,
	precis TEXT,
	synopsis TEXT,
	notes TEXT,
	color TEXT,
	created TEXT DEFAULT CURRENT_TIMESTAMP,
	modified TEXT DEFAULT CURRENT_TIMESTAMP,
	novelid INTEGER,
	FOREIGN KEY(novelid) REFERENCES novel(id)
);


CREATE TABLE annotation(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	content TEXT,
	target TEXT,
	start_index INTEGER,
	end_index INTEGER,
	created TEXT DEFAULT CURRENT_TIMESTAMP,
	modified TEXT DEFAULT CURRENT_TIMESTAMP,
	chapterid INTEGER,
	FOREIGN KEY(chapterid) REFERENCES chapter(id)
);


CREATE TABLE nonce(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	key TEXT,
	value TEXT,
	created TEXT DEFAULT CURRENT_TIMESTAMP
);
